import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { gauntlet } from "../lib/api";
import type { BossSummaryEntry, ObjectionEntry } from "../lib/api";
import { useGameStore } from "../store/gameStore";
import { useChiptune } from "../hooks/useChiptune";

interface SummaryData {
  per_boss: BossSummaryEntry[];
  objections: ObjectionEntry[];
  error?: string;
}

function parseSummary(raw: string): SummaryData | null {
  try {
    const data = JSON.parse(raw) as SummaryData;
    if (Array.isArray(data.per_boss) && Array.isArray(data.objections)) return data;
    return null;
  } catch {
    return null;
  }
}

function buildMarkdown(idea: string, data: SummaryData): string {
  const lines: string[] = [];
  lines.push(`# Idea Mastered: "${idea}"`, "");

  if (data.per_boss.length > 0) {
    lines.push("## Per-Battle Recap", "");
    for (const entry of data.per_boss) {
      lines.push(`### ${entry.name}`, "", entry.summary, "");
    }
  }

  if (data.objections.length > 0) {
    lines.push("## Objections & Counterpoints", "");
    for (const obj of data.objections) {
      lines.push(`### ${obj.objection}`, "");
      if (obj.raised_by.length > 0) {
        lines.push(`*Raised by: ${obj.raised_by.join(", ")}*`, "");
      }
      lines.push(obj.counterpoint, "");
    }
  }

  lines.push("---", "*Generated by Idea Gauntlet*");
  return lines.join("\n");
}

function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function SummaryScreen() {
  const navigate = useNavigate();
  const { session, clearSession } = useGameStore();
  const { unlock, blip } = useChiptune();

  // If session.summary already exists, parse it immediately
  const existing = session?.summary ? parseSummary(session.summary) : null;

  const [perBossMap, setPerBossMap] = useState<Record<string, BossSummaryEntry>>(
    existing ? Object.fromEntries(existing.per_boss.map((e) => [e.name, e])) : {},
  );
  const [objections, setObjections] = useState<ObjectionEntry[]>(existing?.objections ?? []);
  const [objectionsLoading, setObjectionsLoading] = useState(!existing);
  const [error, setError] = useState<string | null>(null);
  // How many boss summaries are still in-flight
  const pendingRef = useRef(0);

  useEffect(() => {
    if (!session) {
      navigate("/", { replace: true });
      return;
    }

    // Already generated — just play the unlock sound and bail
    if (session.summary) {
      unlock();
      return;
    }

    const defeatedBosses = session.bosses.filter((b) => b.status === "defeated");
    if (defeatedBosses.length === 0) {
      setError("No defeated bosses.");
      return;
    }

    // Collect results as they arrive; used for final assembly after all settle
    const collectedBosses: BossSummaryEntry[] = [];
    let collectedObjections: ObjectionEntry[] = [];

    // Fire one call per boss in parallel; update UI as each resolves
    const bossPromises = defeatedBosses.map((boss) =>
      gauntlet
        .bossSummary(session.id, boss.id)
        .then((entry) => {
          collectedBosses.push(entry);
          setPerBossMap((prev) => ({ ...prev, [entry.name]: entry }));
        })
        .catch(() => {
          // Skip failed boss — don't block the rest
        }),
    );

    // Fire objections in parallel with boss summaries
    const objectionsPromise = gauntlet
      .objectionsSummary(session.id)
      .then(({ objections: obj }) => {
        collectedObjections = obj;
        setObjections(obj);
      })
      .catch(() => setError("Failed to generate objections synthesis."))
      .finally(() => setObjectionsLoading(false));

    // When everything settles, assemble ordered JSON and store
    void Promise.allSettled([...bossPromises, objectionsPromise]).then(async () => {
      // Sort per-boss results to match the original boss order
      const ordered = defeatedBosses
        .map((b) => collectedBosses.find((e) => e.name === b.agent.name))
        .filter(Boolean) as BossSummaryEntry[];

      const data = JSON.stringify({ per_boss: ordered, objections: collectedObjections });
      try {
        await gauntlet.storeSummary(session.id, data);
      } catch {
        // Non-critical — the display already shows the data
      }
      unlock();
    });
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  if (!session) return null;

  const defeatedBosses = session.bosses.filter((b) => b.status === "defeated");
  const perBoss = defeatedBosses
    .map((b) => perBossMap[b.agent.name])
    .filter(Boolean) as BossSummaryEntry[];
  const summaryData: SummaryData | null =
    perBoss.length > 0 || objections.length > 0
      ? { per_boss: perBoss, objections }
      : null;

  const handleNewGame = () => {
    blip();
    clearSession();
    navigate("/");
  };

  const handleDownload = () => {
    if (!summaryData) return;
    const content = buildMarkdown(session.idea, summaryData);
    const slug = session.idea.slice(0, 32).replace(/[^a-z0-9]+/gi, "-").toLowerCase();
    downloadMarkdown(`idea-gauntlet-${slug}.md`, content);
  };

  return (
    <div className="screen" style={{ gap: 32, maxWidth: 720, margin: "0 auto" }}>
      <div style={{ textAlign: "center" }}>
        <div style={{ fontSize: 64, marginBottom: 12 }}>⭐</div>
        <h1 className="text-yellow animate-glow" style={{ fontSize: "1.1rem", marginBottom: 8 }}>
          IDEA MASTERED
        </h1>
        <p style={{ fontSize: "0.65rem", color: "var(--nes-gray)" }}>
          ALL CRITICS DEFEATED — SYNTHESIS UNLOCKED
        </p>
      </div>

      {/* Original idea */}
      <div className="pixel-box pixel-box--yellow" style={{ width: "100%", textAlign: "center" }}>
        <p style={{ fontSize: "0.6rem", color: "var(--nes-yellow)", marginBottom: 8 }}>YOUR IDEA:</p>
        <p style={{ fontSize: "0.75rem", lineHeight: 2 }}>"{session.idea}"</p>
      </div>

      {/* Summary */}
      <div className="pixel-box" style={{ width: "100%" }}>
        <p style={{ fontSize: "0.7rem", color: "var(--nes-cyan)", marginBottom: 16 }}>
          FINAL SYNTHESIS:
        </p>

        {error && (
          <p style={{ fontSize: "0.7rem", color: "var(--nes-red)", marginBottom: 12 }}>{error}</p>
        )}

        {/* Per-boss recap — fills in as each boss resolves, in original boss order */}
        {(perBoss.length > 0 || (!session.summary && defeatedBosses.length > 0)) && (
          <div style={{ marginBottom: 24 }}>
            <p style={{ fontSize: "0.65rem", color: "var(--nes-yellow)", marginBottom: 12 }}>
              PER-BATTLE RECAP:
            </p>
            <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
              {defeatedBosses.map((boss) => {
                const entry = perBossMap[boss.agent.name];
                if (entry) {
                  return (
                    <div key={boss.id} style={{ borderLeft: "3px solid var(--nes-cyan)", paddingLeft: 12 }}>
                      <p style={{ fontSize: "0.6rem", color: "var(--nes-cyan)", marginBottom: 4 }}>
                        {boss.agent.emoji} {entry.name}
                      </p>
                      <p style={{ fontSize: "0.7rem", lineHeight: 2, color: "var(--nes-white)" }}>
                        {entry.summary}
                      </p>
                    </div>
                  );
                }
                if (!session.summary) {
                  return (
                    <div key={boss.id} style={{ borderLeft: "3px solid var(--nes-gray)", paddingLeft: 12 }}>
                      <p style={{ fontSize: "0.6rem", color: "var(--nes-gray)", marginBottom: 4 }}>
                        {boss.agent.emoji} {boss.agent.name}
                      </p>
                      <p
                        style={{
                          fontSize: "0.65rem",
                          color: "var(--nes-gray)",
                          animation: "blink 800ms step-start infinite",
                        }}
                      >
                        ANALYZING...
                      </p>
                    </div>
                  );
                }
                return null;
              })}
            </div>
          </div>
        )}

        {/* Objections synthesis */}
        <div>
          <p style={{ fontSize: "0.65rem", color: "var(--nes-yellow)", marginBottom: 12 }}>
            OBJECTIONS & COUNTERPOINTS:
          </p>
          {objectionsLoading && !session.summary ? (
            <p
              style={{
                fontSize: "0.7rem",
                color: "var(--nes-gray)",
                animation: "blink 800ms step-start infinite",
              }}
            >
              GENERATING SYNTHESIS...
            </p>
          ) : (
            <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
              {objections.map((obj, i) => (
                <div key={i} style={{ borderLeft: "3px solid var(--nes-gray)", paddingLeft: 12 }}>
                  <p
                    style={{
                      fontSize: "0.65rem",
                      color: "var(--nes-white)",
                      marginBottom: 4,
                      lineHeight: 1.8,
                    }}
                  >
                    {obj.objection}
                  </p>
                  {obj.raised_by.length > 0 && (
                    <p style={{ fontSize: "0.55rem", color: "var(--nes-gray)", marginBottom: 6 }}>
                      raised by: {obj.raised_by.join(", ")}
                    </p>
                  )}
                  <p style={{ fontSize: "0.65rem", lineHeight: 2, color: "var(--nes-green)" }}>
                    {obj.counterpoint}
                  </p>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Legacy plain-text fallback */}
        {session.summary && !parseSummary(session.summary) && (
          <div
            style={{
              fontSize: "0.75rem",
              lineHeight: 2.2,
              color: "var(--nes-white)",
              whiteSpace: "pre-wrap",
            }}
          >
            {session.summary}
          </div>
        )}
      </div>

      {/* Actions */}
      <div style={{ display: "flex", gap: 16, flexWrap: "wrap", justifyContent: "center" }}>
        {summaryData && (
          <button
            className="pixel-btn"
            onClick={handleDownload}
            style={{ fontSize: "0.75rem", padding: "12px 24px" }}
          >
            ↓ DOWNLOAD .MD
          </button>
        )}
        <button
          className="pixel-btn pixel-btn--green"
          onClick={handleNewGame}
          style={{ fontSize: "0.9rem", padding: "14px 32px" }}
        >
          ► NEW GAME
        </button>
      </div>
    </div>
  );
}
